version: '3'

services:
  
  backend:
    build: ./api
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    command:
      npm start

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=travelAgencyDB
    volumes:
      - ./api/data/db:/var/lib/postgresql/data/

    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./api/data/pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

    

